/**
 * Item catalogue shared by the game engine (inventory, harvest yields) and the
 * database layer (the `inventory` jsonb column). `shared` is the only package
 * both of them depend on, so the catalogue lives here.
 */
export type ItemId =
  | "wood"
  | "stone"
  | "ore"
  | "fiber"
  | "flower"
  | "wheat_seed"
  | "wheat"
  | "carrot_seed"
  | "carrot"
  | "melon_seed"
  | "melon"
  | "fence"
  | "chest"
  | "path_stone"
  | "fishing_rod"
  | "fish_common"
  | "fish_rare"
  | "fish_tropical"
  | "bread"
  | "fish_pie"
  | "carrot_soup"
  | "fruit_salad"
  | "animal_feed"
  | "pet_treat"
  | "house_deed"
  | "table"
  | "chair"
  | "bed"
  | "lamp"
  | "bookshelf"
  | "rug"
  | "painting"
  | "plant_pot"
  | "window_curtain";

export interface ItemDefinition {
  id: ItemId;
  displayName: string;
  stackSize: number;
  /**
   * Numeric `TileType` this item turns its target tile into when placed.
   * Kept as a plain number because `TileType` lives in `@worldnest/game-engine`,
   * which depends on this package.
   */
  placeableTile?: number;
  /** Set when the item places a structure entity rather than changing the tile. */
  placeableStructure?: boolean;
  /** Whether the placed structure blocks movement. Read for structures only. */
  structureCollidable?: boolean;
  /** Texture key of the placed structure, generated by the client. */
  structureTextureKey?: string;
  /** Whether this item can be placed as interior furniture. */
  placeable_furniture?: boolean;
}

export const ITEM_DEFINITIONS: Record<ItemId, ItemDefinition> = {
  wood: { id: "wood", displayName: "Wood", stackSize: 99 },
  stone: { id: "stone", displayName: "Stone", stackSize: 99 },
  ore: { id: "ore", displayName: "Ore", stackSize: 99 },
  fiber: { id: "fiber", displayName: "Fiber", stackSize: 99 },
  flower: { id: "flower", displayName: "Flower", stackSize: 99 },
  wheat_seed: { id: "wheat_seed", displayName: "Wheat Seed", stackSize: 50 },
  wheat: { id: "wheat", displayName: "Wheat", stackSize: 99 },
  carrot_seed: { id: "carrot_seed", displayName: "Carrot Seed", stackSize: 50 },
  carrot: { id: "carrot", displayName: "Carrot", stackSize: 99 },
  melon_seed: { id: "melon_seed", displayName: "Melon Seed", stackSize: 50 },
  melon: { id: "melon", displayName: "Melon", stackSize: 99 },
  fence: {
    id: "fence",
    displayName: "Fence",
    stackSize: 50,
    placeableStructure: true,
    structureCollidable: true,
    structureTextureKey: "structure_fence",
  },
  chest: {
    id: "chest",
    displayName: "Chest",
    stackSize: 10,
    placeableStructure: true,
    structureCollidable: true,
    structureTextureKey: "structure_chest",
  },
  path_stone: {
    id: "path_stone",
    displayName: "Path Stone",
    stackSize: 50,
    placeableTile: 12,
  },
  fishing_rod: { id: "fishing_rod", displayName: "Fishing Rod", stackSize: 1 },
  fish_common: { id: "fish_common", displayName: "Common Fish", stackSize: 50 },
  fish_rare: { id: "fish_rare", displayName: "Rare Fish", stackSize: 50 },
  fish_tropical: {
    id: "fish_tropical",
    displayName: "Tropical Fish",
    stackSize: 50,
  },
  bread: { id: "bread", displayName: "Bread", stackSize: 20 },
  fish_pie: { id: "fish_pie", displayName: "Fish Pie", stackSize: 10 },
  carrot_soup: { id: "carrot_soup", displayName: "Carrot Soup", stackSize: 10 },
  fruit_salad: {
    id: "fruit_salad",
    displayName: "Fruit Salad",
    stackSize: 10,
  },
  animal_feed: {
    id: "animal_feed",
    displayName: "Animal Feed",
    stackSize: 30,
  },
  pet_treat: {
    id: "pet_treat",
    displayName: "Pet Treat",
    stackSize: 20,
  },
  house_deed: {
    id: "house_deed",
    displayName: "House Deed",
    stackSize: 1,
  },
  table: {
    id: "table",
    displayName: "Table",
    stackSize: 10,
    placeable_furniture: true,
  },
  chair: {
    id: "chair",
    displayName: "Chair",
    stackSize: 10,
    placeable_furniture: true,
  },
  bed: {
    id: "bed",
    displayName: "Bed",
    stackSize: 5,
    placeable_furniture: true,
  },
  lamp: {
    id: "lamp",
    displayName: "Lamp",
    stackSize: 10,
    placeable_furniture: true,
  },
  bookshelf: {
    id: "bookshelf",
    displayName: "Bookshelf",
    stackSize: 5,
    placeable_furniture: true,
  },
  rug: {
    id: "rug",
    displayName: "Rug",
    stackSize: 10,
    placeable_furniture: true,
  },
  painting: {
    id: "painting",
    displayName: "Painting",
    stackSize: 10,
    placeable_furniture: true,
  },
  plant_pot: {
    id: "plant_pot",
    displayName: "Plant Pot",
    stackSize: 10,
    placeable_furniture: true,
  },
  window_curtain: {
    id: "window_curtain",
    displayName: "Window Curtain",
    stackSize: 10,
    placeable_furniture: true,
  },
};

export const ITEM_IDS = Object.keys(ITEM_DEFINITIONS) as ItemId[];

/**
 * Whether a value names a catalogue item. Persisted data (the `inventory` jsonb
 * column, `structures.item_id`) is untyped, so it has to be validated on the
 * way back in — an item removed from the catalogue must not crash a session.
 */
export function isItemId(value: unknown): value is ItemId {
  return typeof value === "string" && value in ITEM_DEFINITIONS;
}

/** Items that can be placed in the world as a structure. */
export function isPlaceableStructure(itemId: ItemId): boolean {
  return ITEM_DEFINITIONS[itemId].placeableStructure === true;
}

/** Every placeable structure item, in catalogue order. */
export const PLACEABLE_ITEM_IDS = ITEM_IDS.filter(isPlaceableStructure);
