import { MAX_ENERGY } from "@worldnest/shared";
import { Component } from "../ecs/Component";

const DEFAULT_MAX_HEALTH = 100;

/** Energy recovered per in-game minute at rest. */
const DEFAULT_REGEN_PER_MINUTE = 1;

/**
 * Health and energy for an entity. Energy is spent by interactions (harvesting,
 * planting, building) and regenerated by StatsSystem.
 */
export class StatsComponent extends Component {
  public health: number;
  public maxHealth: number;
  public energy: number;
  public maxEnergy: number;
  public regenPerMinute: number;

  constructor(
    maxHealth: number = DEFAULT_MAX_HEALTH,
    maxEnergy: number = MAX_ENERGY,
    regenPerMinute: number = DEFAULT_REGEN_PER_MINUTE,
  ) {
    super("stats");
    this.maxHealth = maxHealth;
    this.health = maxHealth;
    this.maxEnergy = maxEnergy;
    this.energy = maxEnergy;
    this.regenPerMinute = regenPerMinute;
  }
}
